-- =========================================
-- CREED - REFERRAL / AFFILIATE SCHEMA
-- Run this SQL in the Supabase SQL Editor
-- =========================================

-- 1. Affiliates (the people/partners who get a referral link)
CREATE TABLE IF NOT EXISTS affiliates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,          -- short slug used in ?ref=CODE links
    name TEXT NOT NULL,                 -- affiliate display name
    note TEXT,                          -- optional internal note (contact, platform, etc.)
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_affiliates_code ON affiliates(code);

-- 2. Click / visit log (one row per referred visitor arrival)
CREATE TABLE IF NOT EXISTS affiliate_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,                 -- affiliate code from the link
    landing_path TEXT,                  -- page the visitor landed on
    referrer TEXT,                      -- document.referrer, if any
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_code ON affiliate_clicks(code);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_created_at ON affiliate_clicks(created_at DESC);

-- 3. Attribute orders back to an affiliate
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'orders' AND column_name = 'referral_code'
    ) THEN
        ALTER TABLE orders ADD COLUMN referral_code TEXT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_orders_referral_code ON orders(referral_code);

-- 4. Row Level Security — serverless functions use the service role key
ALTER TABLE affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_clicks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role full access affiliates" ON affiliates;
CREATE POLICY "Service role full access affiliates" ON affiliates
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access affiliate_clicks" ON affiliate_clicks;
CREATE POLICY "Service role full access affiliate_clicks" ON affiliate_clicks
    FOR ALL USING (true) WITH CHECK (true);
